### ISSUE TITLE
certificate expired

### ISSUE THREAD

**Issue by tkelman** [staticfloat/status.julialang.org#24]
cc @staticfloat looks like the let's encrypt certificate was only valid until may 15th. Will try to migrate anyone who doesn't need to use status.julialang.org off of it, but this should probably be fixed if renewal isn't much of an issue.

**Comment by staticfloat** [comment]
Whoops, this fell through the cracks on my most recent certificate renewal spree.  At least I got `cache`.  :P

This is now fixed.

**Comment by tkelman** [comment]
Great, thanks. How long was the renewal for?

**Comment by staticfloat** [comment]
We get a certificate for 3 months, but they have recently upgraded their software to allow for automatic renewals, so I should add a cron job for that.
